In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp38-cp38-macosx_10_9_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from scikit-learn) (1.24.4)
Collecting scipy>=1.5.0 (from scikit-learn)
  Downloading scipy-1.10.1-cp38-cp38-macosx_10_9_x86_64.whl.metadata (53 kB)
Collecting joblib>=1.1.1 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.3.2-cp38-cp38-macosx_10_9_x86_64.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 5.4 MB/s eta 0:00:00 0:00:01m
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.10.1-cp38-cp38-macosx_10_9_x86_64.whl (35.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 10.9 MB/s eta 0:00:0000:0100:01
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.3.2 scipy-1.10.1 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
# Modelling packages

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import RandomizedSearchCV

In [49]:
from sklearn.metrics import mean_absolute_error

In [4]:
df = pd.read_csv('/Users/rohitalexkoshy/Downloads/Data Science/3_Projects/notebook/data/stud.csv')

In [9]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.7-cp38-cp38-macosx_11_0_universal2.whl.metadata (1.2 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from catboost) (3.7.5)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from catboost) (1.24.4)
Requirement already satisfied: pandas>=0.24 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from catboost) (2.0.3)
Requirement already satisfied: scipy in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from catboost) (1.10.1)
Collecting plotly (from catboost)
  Downloading plotly-5.24.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from pandas>=0.24->catboost) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from pandas>=0.24->catboost) (2024.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (3.1.4)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from matplotlib->catboost) (6.4.5)
Collecting tenacity>=6.2.0 (from plotly->catboost)
  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: zipp>=3.1.0 in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->catboost) (3.20.2)
Downloading catboost-1.2.7-cp38-cp38-macosx_11_0_universal2.whl (27.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.1/27.1 MB 4.2 MB/s eta 0:00:0000:0100:01
Downloading graphviz-0.20.3-py3-none-any.whl (47 kB)
Downloading plotly-5.24.1-py3-none-any.whl (19.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 10.8 MB/s eta 0:00:0000:0100:01
Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
Installing collected packages: tenacity, graphviz, plotly, catboost
Successfully installed catboost-1.2.7 graphviz-0.20.3 plotly-5.24.1 tenacity-9.0.0
Note: you may need to restart the kernel to use updated packages.

In [10]:
from catboost import CatBoostRegressor

In [11]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-2.1.3-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from xgboost) (1.24.4)
Requirement already satisfied: scipy in /Users/rohitalexkoshy/Downloads/Data Science/3_Projects/venv/lib/python3.8/site-packages (from xgboost) (1.10.1)
Downloading xgboost-2.1.3-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 11.5 MB/s eta 0:00:0000:01
Installing collected packages: xgboost
Successfully installed xgboost-2.1.3
Note: you may need to restart the kernel to use updated packages.

In [22]:
from xgboost import XGBRegressor

In [23]:
df = pd.read_csv('/Users/rohitalexkoshy/Downloads/Data Science/3_Projects/notebook/data/stud.csv')

In [24]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [25]:
X = df.drop('math_score', axis=1)
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [27]:
y = df['math_score']
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math_score, dtype: int64

In [28]:
X.shape, y.shape

((1000, 7), (1000,))

In [29]:
df.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [30]:
df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [31]:
df['race_ethnicity'].value_counts()

race_ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [32]:
df['parental_level_of_education'].value_counts()

parental_level_of_education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [33]:
df['lunch'].value_counts()

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [34]:
df['test_preparation_course'].value_counts()

test_preparation_course
none         642
completed    358
Name: count, dtype: int64

In [35]:
num_features = [features for features in X.columns if X[features].dtype!="O" ]
cat_features = [features for features in X.columns if X[features].dtype=="O"]

In [36]:
num_features

['reading_score', 'writing_score']

In [37]:
cat_features

['gender',
 'race_ethnicity',
 'parental_level_of_education',
 'lunch',
 'test_preparation_course']

In [39]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder()

In [41]:
from sklearn.compose import ColumnTransformer

In [42]:
preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", categorical_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [43]:
X = preprocessor.fit_transform(X)

In [44]:
X

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]])

In [45]:
X.shape

(1000, 19)

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
## Separate the dataset into train and test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=42)
X_train.shape, X_test.shape

((800, 19), (200, 19))

In [48]:
y_train.shape, y_test.shape

((800,), (200,))

In [60]:
## Evaluate function to give metrics after model training

def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [52]:
models = {
    "LinearRegression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XG Boost Regressor": XGBRegressor(),
    "Catboost Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}

model_list = []
r2_list = []

In [66]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) #Train the model
    
    #Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error:{:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error:{:.4f}".format(model_train_mae))
    print("- R2 Score:{:4f}".format(model_train_r2))

    print('-'*35)

    print('Model performance for Test set')
    print("- Root Mean Squared Error:{:.4f}".format(model_test_mae))
    print("- Mean Absolute Error:{:.4f}".format(model_test_mae))
    print("- R2 Score:{:4f}".format(model_test_r2))
    r2_list.append(model_test_r2)

    print('='*35)
    print('\n')

LinearRegression
Model performance for Training set
- Root Mean Squared Error:5.3231
- Mean Absolute Error:4.2667
- R2 Score:0.874317
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:4.2148
- Mean Absolute Error:4.2148
- R2 Score:0.880433
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error:6.5938
- Mean Absolute Error:5.2063
- R2 Score:0.807146
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:5.1579
- Mean Absolute Error:5.1579
- R2 Score:0.825320
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error:5.3233
- Mean Absolute Error:4.2650
- R2 Score:0.874304
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:4.2111
- Mean Absolute Error:4.2111
- R2 Score:0.880593
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error:5.7091
- Mean Absolute Error:4.5175
- R2 Score:0.855428
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:5.6370
- Mean Absolute Error:5.6370
- R2 Score:0.783497
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error:0.2795
- Mean Absolute Error:0.0187
- R2 Score:0.999653
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:6.2550
- Mean Absolute Error:6.2550
- R2 Score:0.742560
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error:2.2988
- Mean Absolute Error:1.8345
- R2 Score:0.976561
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:4.5754
- Mean Absolute Error:4.5754
- R2 Score:0.854597
===================================


XG Boost Regressor
Model performance for Training set
- Root Mean Squared Error:1.0073
- Mean Absolute Error:0.6875
- R2 Score:0.995500
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:5.0577
- Mean Absolute Error:5.0577
- R2 Score:0.827797
===================================


Catboost Regressor
Model performance for Training set
- Root Mean Squared Error:3.0427
- Mean Absolute Error:2.4054
- R2 Score:0.958936
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:4.6125
- Mean Absolute Error:4.6125
- R2 Score:0.851632
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error:5.8615
- Mean Absolute Error:4.8169
- R2 Score:0.847607
-----------------------------------
Model performance for Test set
- Root Mean Squared Error:4.6734
- Mean Absolute Error:4.6734
- R2 Score:0.850162
===================================

In [65]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)